global:
  file_watch_config:
    min_poll_frequency: 250
    max_poll_frequency: 250
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-logs
          __path__: /var/logs/springboot/*.log
  - job_name: nestjs-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nestjs-logs
          __path__: /var/logs/nestjs/*.log